# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: Juan Ríos 
# Edit next line, replacing 'techfolios' with your github username
name: "My corner of the universe"
description: "A blog about tech, computers and dreams"
url: "https://juandarr.github.io"
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
bio-page-label: Resume
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: theme-home.html
theme-projects: theme-projects.html
theme-essays: theme-essays.html
theme-bio: theme-bio.html
theme-tags: theme-tags.html

# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

# Homepage limit posts
number_of_posts: 6
