# Site-specific settings
#  Edit next line with your name.
title: Philip Johnson | Professional Portfolio
# Edit next line with your github username
url: "https://techfolios.github.io"

# The following lines contain global defaults you don't normally need to change.
baseurl: "/template" # change this to "/<repo>" if your portfolio is the <username>.github.io repo.
markdown: kramdown
include: [_data]

